controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
      - joint_8
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: zero_post
  - group: hand
    pose: hand_closed